CREATE TABLE IF NOT EXISTS bot_servers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_key       TEXT NOT NULL UNIQUE,
    url              TEXT NOT NULL UNIQUE,
    user_id          TEXT,
    tariff           TEXT,
    tariff_period    TEXT,
    payment_date     TEXT,
    connected        BOOLEAN NOT NULL DEFAULT FALSE,
    license_id       TEXT,
    lease            TEXT,
    lease_sig        TEXT,
    lease_kid        TEXT,
    lease_exp        BIGINT,
    token_configured BOOLEAN NOT NULL DEFAULT FALSE,
    token_valid      BOOLEAN,
    status           TEXT NOT NULL DEFAULT 'offline',
    version          TEXT,
    fingerprint      TEXT,
    last_seen_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bots (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id      BIGINT NOT NULL REFERENCES bot_servers(id) ON DELETE CASCADE,
    user_id        TEXT NOT NULL,
    ticker         TEXT NOT NULL,
    class_code     TEXT NOT NULL DEFAULT 'TQBR',
    p_low          DOUBLE PRECISION NOT NULL,
    p_high         DOUBLE PRECISION NOT NULL,
    capital        DOUBLE PRECISION NOT NULL,
    n              INTEGER NOT NULL,
    desired_state  TEXT NOT NULL DEFAULT 'run',
    sell_on_delete BOOLEAN NOT NULL DEFAULT FALSE,
    status         TEXT NOT NULL DEFAULT 'created',
    remote_bot_id  INTEGER,
    current_price  DOUBLE PRECISION,
    initial_lots   INTEGER,
    cash_remaining DOUBLE PRECISION,
    error          TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bots_server ON bots(server_id);
CREATE INDEX IF NOT EXISTS idx_bots_user ON bots(user_id);

CREATE TABLE IF NOT EXISTS bot_trades (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_config_id    BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
    server_id        BIGINT NOT NULL,
    user_id          TEXT NOT NULL,
    remote_trade_id  INTEGER NOT NULL,
    remote_bot_id    INTEGER,
    ticker           TEXT,
    direction        TEXT NOT NULL,
    lots             INTEGER NOT NULL,
    lot_size         INTEGER NOT NULL DEFAULT 1,
    price_per_share  DOUBLE PRECISION NOT NULL DEFAULT 0,
    quantity_shares  INTEGER NOT NULL DEFAULT 0,
    total_amount     DOUBLE PRECISION NOT NULL DEFAULT 0,
    commission       DOUBLE PRECISION NOT NULL DEFAULT 0,
    executed_at      TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (server_id, remote_trade_id)
);
CREATE INDEX IF NOT EXISTS idx_bot_trades_bot ON bot_trades(bot_config_id);
CREATE INDEX IF NOT EXISTS idx_bot_trades_user ON bot_trades(user_id);

CREATE TABLE IF NOT EXISTS bot_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id      BIGINT NOT NULL,
    user_id        TEXT,
    bot_config_id  BIGINT,
    remote_bot_id  INTEGER,
    level          TEXT NOT NULL DEFAULT 'INFO',
    message        TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bot_logs_server ON bot_logs(server_id);
CREATE INDEX IF NOT EXISTS idx_bot_logs_user ON bot_logs(user_id);
